#!/usr/bin/env python3

import os
import sys
import getpass
import pexpect
import time
import signal
import configparser

def absolute_path(file):
	 script = os.path.realpath(__file__)
	 script_path_elements = script.split('/')
	 script_path_elements = script_path_elements [:-1]
	 script_path_elements.append(file)
	 return '/'.join(script_path_elements)

def printer(message):
	print('%s' % message)

if os.path.exists(absolute_path('config.ini')):
	config = configparser.ConfigParser()
	config.read(absolute_path('config.ini'))
else:
	printer('No config.ini exists. Make sure you edit and rename config.ini.default')
	exit(1)

try:
	user = config.get('SSH Host', 'User')
except configparser.NoOptionError:
	printer('Error: SSH User undefined. Correct in config.ini and try again')
	exit(1)

try:
	host = config.get('SSH Host', 'Host')
except configparser.NoOptionError:
	printer('Error: SSH Host undefined. Correct in config.ini and try again')
	exit(1)

try:
	port = config.get('Proxy', 'Port')
except configparser.NoOptionError:
	printer('Error: Proxy port undefined. Correct in config.ini and try again')
	exit(1)

ssh_command = 'ssh -C2qTnN -D %s -o PreferredAuthentications=keyboard-interactive,password -o PubkeyAuthentication=no -f %s@%s' % (port, user, host)

def run_command(arg):
	if '--start' == arg:
		start()
	elif '--stop' == arg:
		stop()
	elif '--restart' == arg:
		restart()
	elif '--status' == arg:
		status()
	else:
		print('USAGE: %s [--start,--stop,--restart, --status]' % sys.argv[0])

def get_pids():
	ps = pexpect.run('ps -ax')
	pids = []

	for line in ps.splitlines():
		if str(line).find('ssh -C2qTnN -D %s' % port) > 0:
			line_split = str(line).split(' ')
			pids.append(line_split[0][2:])

	if len(pids) > 0:
		return pids
	
	return False

def start():
	if not (get_pids()):
		printer('SSH Proxy starting...')
		password = getpass.getpass(prompt='SSH password for %s: ' % user)
		
		try:
			ssh_tunnel = pexpect.spawn (ssh_command % globals())
			ssh_tunnel.expect ('password:')
			time.sleep (0.1)
			ssh_tunnel.sendline (password)
			time.sleep (0.1)
			ssh_tunnel.expect (pexpect.EOF)

		except Exception as e:
			print('Error: Unable to create tunnel. Try running the command manually for details:')
			printer(ssh_command)

		status()
	else:
		printer('SSH Proxy is already running')

def stop():
	printer('SSH Proxy stopping...')
	pids = get_pids()
	if pids:
		for pid in pids:
			os.kill(int(pid), signal.SIGTERM)

	if get_pids():
		printer('Error: Unable to stop SSH Proxy. Please try again')

def restart():
	stop()
	start()
	pass

def status():
	if get_pids():
		printer('SSH Proxy is currently connected, via %s' % host)
	else:
		printer('SSH Proxy is not connected')
	pass

try:
	if len(sys.argv) == 2:
		command = run_command(sys.argv[1])
	else:
		command = run_command('--help')
except KeyboardInterrupt:
	print('')
	exit(1)