#!/usr/bin/env python3

import os
import sys
import getpass
import pexpect
import time
import signal
import configparser

def absolute_path(file):
	 script = os.path.realpath(__file__)
	 script_path_elements = script.split('/')
	 script_path_elements = script_path_elements [:-1]
	 script_path_elements.append(file)
	 return '/'.join(script_path_elements)

def printer(message):
	print('%s' % message)

if os.path.exists(absolute_path('config.ini')):
	configs = configparser.ConfigParser()
	configs.read(absolute_path('config.ini'))
else:
	printer('No config.ini exists. Make sure you edit and rename config.ini.default')
	exit(1)

num_configs = len(configs.sections())
if num_configs == 0:
	printer('No configs found')
	exit(1)

for config in configs.sections():
	try:
		user = configs.get(config, 'User')
	except configparser.NoOptionError:
		printer('Error: User undefined in \'%s\' config. Correct in config.ini and try again' % config)
		exit(1)

	try:
		host = configs.get(config, 'Host')
	except configparser.NoOptionError:
		printer('Error: Host undefined in \'%s\' config. Correct in config.ini and try again' % config)
		exit(1)

	try:
		port = configs.get(config, 'Port')
	except configparser.NoOptionError:
		printer('Error: Proxy port undefined in \'%s\' config. Correct in config.ini and try again' % config)
		exit(1)

def run_command(arg):
	if '--start' == arg:
		start()
	elif '--stop' == arg:
		stop()
	elif '--restart' == arg:
		restart()
	elif '--status' == arg:
		status()
	else:
		print('USAGE: %s [--start,--stop,--restart, --status]' % sys.argv[0])

def get_pids():
	ps = pexpect.run('ps -ax')
	pids = []

	for line in ps.splitlines():
		if str(line).find('ssh -C2qTnN -D') > 0:
			line_split = str(line).split(' ')
			pids.append(line_split[0][2:])

	if len(pids) > 0:
		return pids
	
	return False

def start():
	if not (get_pids()):
		printer('SSH Proxy starting...')
		
		for config in configs.sections():
			user = configs.get(config, 'User')
			host = configs.get(config, 'Host')
			port = configs.get(config, 'Port')

			ssh_command = 'ssh -C2qTnN -D %s -o PreferredAuthentications=keyboard-interactive,password -o PubkeyAuthentication=no -f %s@%s' % (port, user, host)

			try:
				printer('Connecting to %s...' % config)
				ssh_tunnel = pexpect.spawn (ssh_command % globals())
				ssh_tunnel.expect ('password:')
				time.sleep (0.1)
				password = getpass.getpass(prompt='SSH password for %s: ' % user)
				printer('Connecting...')
				ssh_tunnel.sendline (password)
				time.sleep (0.1)
				ssh_tunnel.expect (pexpect.EOF)
				if(get_pids()):
					printer('Connected to %s' % config)

			except Exception as e:
				print('Error: Unable to create tunnel. Try running the command manually for details:')
				printer(ssh_command)
			
	else:
		printer('SSH Proxy is already connected')

def stop():
	printer('SSH Proxy stopping...')
	pids = get_pids()
	if pids:
		for pid in pids:
			os.kill(int(pid), signal.SIGTERM)

	if get_pids():
		printer('Error: Unable to stop SSH Proxy. Please try again')

def restart():
	stop()
	start()
	pass

def status():
	if get_pids():
		printer('SSH Proxy is currently connected')
	else:
		printer('SSH Proxy is not connected')
	pass

try:
	if len(sys.argv) == 2:
		command = run_command(sys.argv[1])
	else:
		command = run_command('--help')
except KeyboardInterrupt:
	print('')
	exit(1)